# Generated by Django 5.0.2 on 2024-02-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('result', models.IntegerField(choices=[(0, 'Undefined'), (1, 'In Progress'), (2, 'Defeat'), (3, 'Victory')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('profile_picture', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=3, max_digits=6)),
                ('y', models.DecimalField(decimal_places=3, max_digits=6)),
                ('hit', models.BooleanField()),
                ('dx', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('dy', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSApp.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSApp.user')),
            ],
        ),
    ]
